export const CREATE_EVENT = 'CREATE_EVENT'
export const DELETE_EVENT = 'DELETE_EVENT'

export const SET_TARGETDATE = 'SET_TARGETDATE'
export const SET_INPUTEVENTOBJECT = 'SET_INPUTEVENTOBJECT'
export const SET_POPOVERSTATE = 'SET_POPOVERSTATE'
